name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --base-href /tango/ --pwa-strategy=none

      - run: |
          git config --global user.name "mizunohirune"
          git config --global user.email "mizunohirune@example.com"

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          force_orphan: true